# Generated by Django 5.1.4 on 2026-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_alert_id_alter_hardwarespec_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heartbeatlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="cpu_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="disk_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="ram_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="alert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hardwarespec",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="heartbeatlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
