# Generated by Django 5.1.4 on 2026-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_heartbeatlog_options_device_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwarespec",
            name="cpu_cores",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hardwarespec",
            name="cpu_threads",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hardwarespec",
            name="hostname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="hardwarespec",
            name="ip_address",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="battery_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="battery_plugged",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="process_count",
            field=models.IntegerField(default=0),
        ),
    ]
