# Generated by Django 5.1.4 on 2026-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_hardwarespec_cpu_cores_hardwarespec_cpu_threads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeatlog",
            name="cpu_freq",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="cpu_idle",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="cpu_system",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="cpu_user",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="disk_read_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="disk_write_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="memory_available",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="memory_cached",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="memory_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="memory_used",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="net_bytes_recv",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="net_bytes_sent",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="net_packets_recv",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="net_packets_sent",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="swap_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="swap_used",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="heartbeatlog",
            name="top_processes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
