# Generated by Django 5.1.4 on 2026-05-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_add_indexes_and_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='CRITICAL', max_length=10),
        ),
    ]
