# Generated by Django 5.1.4 on 2026-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='went_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
