# Generated by Django 5.1.4 on 2026-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_device_went_online_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeatlog',
            name='cpu_per_core',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
