# Generated by Django 5.1.4 on 2026-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_heartbeat_cpu_per_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeatlog',
            name='cpu_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
