# Generated by Django 5.1.4 on 2026-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_heartbeat_cpu_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeatlog',
            name='disk_partitions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
