# Generated by Django 5.1.4 on 2026-05-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_heartbeat_disk_partitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('cpu_avg', models.FloatField(default=0)),
                ('cpu_max', models.FloatField(default=0)),
                ('ram_avg', models.FloatField(default=0)),
                ('ram_max', models.FloatField(default=0)),
                ('disk_avg', models.FloatField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='monitoring.device')),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['device', '-hour'], name='hourly_device_hour_idx')],
                'unique_together': {('device', 'hour')},
            },
        ),
    ]
